FROM node:13.12.0-alpine

RUN mkdir /tmp/react-container
WORKDIR /tmp/react-container

ENV PATH /tmp/react-container/node-modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

COPY . ./

CMD ["npm","start"]

