# Generated by Django 3.1.5 on 2021-01-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('slug', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('slug', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('original_name', models.TextField()),
                ('anglicized_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.book')),
                ('contributors', models.ManyToManyField(to='appmodule.User')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmodule.language')),
            ],
        ),
    ]
